/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FFMPEGTest */

#ifndef _Included_FFMPEGTest
#define _Included_FFMPEGTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FFMPEGTest
 * Method:    getContext
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_FFMPEGTest_getContext
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FFMPEGTest
 * Method:    mergevideo
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FFMPEGTest_mergevideo
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     FFMPEGTest
 * Method:    cutvideo
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_FFMPEGTest_cutvideo
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     FFMPEGTest
 * Method:    insertvideo
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_FFMPEGTest_insertvideo
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     FFMPEGTest
 * Method:    executemux
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_FFMPEGTest_executemux
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
